# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_auto_20170629_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introductions',
        ),
    ]
